architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/${rootProject.archives_name}.accesswidener")
}

repositories {
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "com.cobblemon:mod:$rootProject.cobblemon_version"
    modCompileOnly "com.necro.asymmetric.battles:asymmetricbattles-common:$rootProject.asymmetricbattles_version"
    modCompileOnly "me.shedaniel.cloth:cloth-config:$rootProject.cloth_config_version"
}